import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center w-screen h-screen p-0 m-0 bg-gray-950 text-gray-50`}
            >
                <main className="flex w-10/12 min-h-fit min-w-fit justify-center items-center h-[70%] bg-gray-800 shadow-gray-700 shadow-md rounded-md p-10">
                    {children}
                </main>
            </body>
        </html>
    );
}
