export const gameStrings = {
    submitButtonText: "▶ Submit Word",
    submitButtonPendingText: "Submitting…",
    gameState: "Game State: ",
    waitingForGameToStart: "Waiting for game to start...",
    startGame: "Start game",
    startingGame: "Starting game…",
    round: "Round ",
    matchLetter: "Match Letter",
    players: "Players",
    emptySeat: "?",
    empty: "Empty",
    inputDisabledText: "Not your turn",
    inputPendingText: "Submitting…",
    inputInvalidText: "Invalid word",
    connectionRequired: "Connection Required",
    pleaseConnectToJoin: "Please connect to join the game",
    connectButtonText: "Connect",
    playIcon: "▶",
    hostLeftTheRoom: "Host left the room",
    returningToLobby: "Returning to lobby…",
    noWinner: "—",
} as const;
